name: 'Bug Report'
description: Report a bug in Box2D .NET Standard
labels: ["bug"]

body:
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: How To Reproduce
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true
