name: Box2D Examples Build

on:
  push:
    branches: [v2.4]
    paths:
      - examples/**
  pull_request:
    branches: [v2.4]
    paths:
      - examples/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"
      - name: Build
        run: dotnet build examples/ -c Release
