name: Box2D Unit Tests

on:
  push:
    branches: [v2.4]
    paths:
      - src/**
  pull_request:
    branches: [v2.4]
    paths:
      - src/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.x"
      - name: Unit Tests
        run: dotnet test src/ -c Release
