name: Build

on:
  push:
    branches: [v2.4]
    paths:
      - src/box2dx/Box2D.NetStandard/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"
      - name: Box2D Build
        run: dotnet build src/box2dx/Box2D.NetStandard -c Release
