name: Build

on:
  push:
    branches: [v2.4]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.1'
      - name: Box2D Build
        run: dotnet build src/ -c Release