name: Unit Tests

on:
  push:
    branches: [v2.4]
  pull_request:
    branches: [v2.4]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Execute Tests
        run: dotnet test src/ -c Release